Map<String, dynamic> ImgMapping = {
  'ASIAN_FOOD': 'assets/images/ASIAN_FOOD.png',
  'CHICKEN': 'assets/images/CHICKEN.png',
  'CHINESE': 'assets/images/CHINESE.png',
  'DESSERT': 'assets/images/DESSERT.png',
  'FASTFOOD': 'assets/images/FASTFOOD.png',
  'JAPANESE': 'assets/images/JAPANESE.png',
  'LUNCH_BOX': 'assets/images/LUNCH_BOX.png',
  'PIG_HOCKS': 'assets/images/PIG_HOCKS.png',
  'PIZZA': 'assets/images/PIZZA.png',
  'PORRIDGE': 'assets/images/PORRIDGE.png',
  'ROAST_FOOD': 'assets/images/ROAST_FOOD.png',
  'SCHOOL_FOOD': 'assets/images/SCHOOL_FOOD.png',
  'STEAM_DISH': 'assets/images/STEAM_DISH.png',
  'WESTERN_FOOD': 'assets/images/WESTERN_FOOD.png',
};

Map<String, dynamic> StringMapping = {
  'ASIAN_FOOD': '아시안',
  'CHICKEN': '치킨',
  'CHINESE': '중식',
  'DESSERT': '디저트',
  'FASTFOOD': '패스트푸드',
  'JAPANESE': '일식',
  'LUNCH_BOX': '도시락',
  'PIG_HOCKS': '족발',
  'PIZZA': '피자',
  'PORRIDGE': '죽',
  'ROAST_FOOD': '고기구이',
  'SCHOOL_FOOD': '분식',
  'STEAM_DISH': '찜',
  'WESTERN_FOOD': '양식',
};

Map<String, dynamic> MappingKorean = {
  '아시안': 'ASIAN_FOOD',
  '치킨': 'CHICKEN',
  '중식': 'CHINESE',
  '디저트': 'DESSERT',
  '패스트푸드': 'FASTFOOD',
  '일식': 'JAPANESE',
  '도시락': 'LUNCH_BOX',
  '족발': 'PIG_HOCKS',
  '피자': 'PIZZA',
  '죽': 'PORRIDGE',
  '고기구이': 'ROAST_FOOD',
  '분식': 'SCHOOL_FOOD',
  '찜': 'STEAM_DISH',
  '양식': 'WESTERN_FOOD',
};
