import 'package:nonamukja/model/auth/register_model.dart';

class UserSingInRepository {
  Autogenerated setUserRepository(Map<String, dynamic> userSignInInfo) {
    return Autogenerated.fromJson({
      'username': userSignInInfo['userName'],
      'email': userSignInInfo['email'],
      'password': userSignInInfo['password'],
      'address': {
        'address': userSignInInfo['address'],
        'roadAddress': userSignInInfo['roadAddress'],
        'zipCode': userSignInInfo['zipCode'],
        'coordinate': {
          'latitude': userSignInInfo['x'],
          'longitude': userSignInInfo['y']
        },
      },
    });
  }
}
