import 'dart:convert';

import 'package:nonamukja/model/register_model.dart';
import 'package:http/http.dart' show Client;

class UserSinginProvieder {
  Client client = Client();

  Future<String> userSinginProvider(Autogenerated autogenerated) async {
    final response = await client.post(
        Uri.parse("http://127.0.0.1:8080/api/v1/auth/register"),
        headers: {"Accept": 'application/json'},
        body: autogenerated.toJson());
    print(response.body.toString());
    if (response.statusCode == 201) {
      return response.body.toString();
    } else {
      // 실패 메시지 출력
      throw Exception('회원가입에 실패 하였습니다.');
    }
  }
}
