import 'dart:convert';

import 'package:nonamukja/model/auth/register_model.dart';
import 'package:http/http.dart' show Client;

class UserSinginProvieder {
  Client client = Client();

  Future<Map<String, dynamic>> userSinginProvider(
      Autogenerated autogenerated) async {
    final response = await client.post(
        Uri.parse("http://127.0.0.1:8080/api/v1/auth/register"),
        headers: {"Content-Type": "application/json"},
        body: jsonEncode(autogenerated));
    if (response.statusCode == 201) {
      return {'statusCode': response.statusCode, 'message': '회원가입 성공'};
    } else {
      // 실패 메시지 출력
      final data = jsonDecode(response.body);
      print(data);
      return {'statusCode': response.statusCode, 'message': data['message']};
    }
  }
}
